apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-auth-pvc
  namespace: cloudcart
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-db-init
  namespace: cloudcart
data:
  init.sql: |
    CREATE TABLE IF NOT EXISTS users (
        id SERIAL PRIMARY KEY,
        name VARCHAR(100) NOT NULL,
        email VARCHAR(150) UNIQUE NOT NULL,
        password VARCHAR(255) NOT NULL,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-auth
  namespace: cloudcart
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-auth
  template:
    metadata:
      labels:
        app: postgres-auth
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: cloudcart-config
                  key: DB_USER

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cloudcart-secrets
                  key: POSTGRES_PASSWORD

            - name: POSTGRES_DB
              value: cloudcart_auth

          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data

            - name: init-script
              mountPath: /docker-entrypoint-initdb.d/init.sql
              subPath: init.sql

          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - pg_isready -U postgres -d cloudcart_auth
            initialDelaySeconds: 5
            periodSeconds: 5

      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-auth-pvc

        - name: init-script
          configMap:
            name: auth-db-init

---

apiVersion: v1
kind: Service
metadata:
  name: postgres-auth
  namespace: cloudcart
spec:
  selector:
    app: postgres-auth
  ports:
    - port: 5432
      targetPort: 5432